az/enrique/config/routes.rb
Rails.application.routes.draw do
  get 'libros/mis-libros', to: "user#index"
  post 'libros/agregar', to: "user#add_book"
  devise_for :users
  root to: "boostore#index"
  get "autores", to: 'author#index'

## Acciones de mi Appi:

get 'appi/libros', to: "appi#books"
get 'appi/libro/:book_id', to: "appi#show"


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

az/enrique/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

az/enrique/app/models/author.rb
class Author < ApplicationRecord
    has_many :books
end

az/enrique/app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
  has_many :userbooks
  has_many :users, through: :userbooks
end

az/enrique/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :userbooks
  has_many :books, through: :userbooks
end

az/enrique/app/models/userbook.rb
class Userbook < ApplicationRecord
    belongs_to :user
    belongs_to :book
end

az/enrique/app/controllers/appi_controller.rb
class AppiController < ApplicationController
    def books
        books = Book.all
        render json: {
            books: books
        }
    end

    def show
        book_id = params[:book_id]
        book = Book.find(book_id)
        render json: {
            id: book.id,
            name: book.name
        }
    end
end

az/enrique/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

az/enrique/app/controllers/author_controller.rb
class AuthorController < ApplicationController
  before_action :authenticate_user!
  def index
    @authors = Author.all
  end
end

az/enrique/app/controllers/boostore_controller.rb
class BoostoreController < ApplicationController
    def index
    end
end

az/enrique/app/controllers/user_controller.rb
class UserController < ApplicationController
    before_action :authenticate_user!
    def index
        @books = current_user.books
end

    def add_book
            book_params = params.require(:book).permit(:id)
            book = Book.find(book_params[:id])
            unless book.nil?
                current_user.books.push(book)
            end
        redirect_to :controller => 'user', :action => 'index'
end
end

az/enrique/app/helpers/appi_helper.rb
module AppiHelper
end

az/enrique/app/helpers/application_helper.rb
module ApplicationHelper
end

az/enrique/app/helpers/author_helper.rb
module AuthorHelper
end

az/enrique/app/helpers/boostore_helper.rb
module BoostoreHelper
end

az/enrique/app/helpers/user_helper.rb
module UserHelper
end

az/enrique/app/views/author/index.html.erb
<h1>Author#index</h1>
<p>Find me in app/views/author/index.html.erb</p>

<ul>
<% for author in @authors %>
    <li>
<%= author.name %>
<ul>    
<% for book in author.books %>
<li>
<%= book.name %>
<form method="post" action="<%= libros_agregar_path %>" >
            <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
            <input type="hidden" name="book[id]" value="<%= book.id %>">
        <button type="submit">Agregar</button>
</form>
</li>
<% end %>
</ul>
</li>
<% end %>
</ul>

az/enrique/app/views/boostore/index.html.erb
<h1>Libreria!</h1>

az/enrique/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Enrique</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% if user_signed_in? %>
  
  <ul>
  
    <li>
      <%= link_to "Logout", destroy_user_session_path, method: :delete, class: 'nav-link' %>
    </li>

    <li>
      <a href="<%= libros_mis_libros_path %>">Mis Libros</a>
    </li>

    <li>
      <a href="<%= autores_path %>">Autores</a>
    </li>
  </ul>
  
  <% else %>
  <a href="<%=new_user_session_path %>">Log in</a>
  <% end %>
    <%= yield %>
    <div class="notice">
    <%= notice %>
</div>
<div class="alert">
    <%= alert %>
</div>
  </body>
</html>

az/enrique/app/views/user/index.html.erb
<h1>User#index</h1>
<p>Find me in app/views/user/index.html.erb</p>

<ul>
    <% for book in @books %>
    <li><%= book.name %></li>
    <% end %>
</ul>